### ISSUE TITLE
parport.markdown file is empty

### ISSUE THREAD

**Issue by humblewizard** [jmendeth/parport.js#2]
The only file under the doc folder is empty. The revision date is 2/3/2015 so we do appreciate the revision. Also I can't find the examples folder that was discussed.

**Comment by mildsunrise** [comment]
The fact is, whenever I start writing an extension, I always create and reference an `examples` directory from `README` and `package.json`.

I still haven't written any examples of the addon (the API is so simple that I didn't think it was necessary), therefore Git is not tracking the `examples` directory and it doesn't appear here.

**Comment by mildsunrise** [comment]
Now when it comes to the docs, that was pending too. I'll do it soon.

**Comment by mildsunrise** [comment]
See https://github.com/jmendeth/parport.js/issues/4#issuecomment-85877759.
