### ISSUE TITLE
readData() not useful. 

### ISSUE THREAD

**Issue by humblewizard** [jmendeth/parport.js#3]
I have the package installed and I can write the port just fine but I can't read data through the port. I can only read back what had been written. Not much value there. How do we get the ECP direction turned around so we can read data from the outside world? The port's output buffer needs to be tristated.

**Comment by humblewizard** [comment]
This is not a problem I got the thing to work. The document
http://users.utcluj.ro/~baruch/media/siee/labor/Standard-Parallel-Port.pdf
had the information I need to figure this out. The control register C5 which is the data direction register needed to be set as in the example.

**Comment by mildsunrise** [comment]
I want the API to be low level, and in fact this is just a thin wrapper around [Parallel-Port](http://parallel-port.googlecode.com), so I'd prefer to leave it as it is now.
